// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class Indices {
    get ffiValue(): pointer;


    static splitNewlines(input: string): Indices;

    getIndices(): Array<bigint>;
}