// generated by diplomat-tool
import { Spliterator } from "./Spliterator.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const LineSplitter_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.LineSplitter_destroy(ptr);
});

export class LineSplitter {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("LineSplitter is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            LineSplitter_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    get ffiValue() {
        return this.#ptr;
    }


    static new_(input) {
        let functionGarbageCollectorGrip = new diplomatRuntime.GarbageCollectorGrip();
        const inputSlice = diplomatRuntime.DiplomatBuf.str8(wasm, input);
        // This lifetime edge depends on lifetimes 'a
        let aEdges = [inputSlice];


        const result = wasm.LineSplitter_new(...inputSlice.splat());

        try {
            return new LineSplitter(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            functionGarbageCollectorGrip.releaseToGarbageCollector();

        }
    }

    spliterator() {
        // This lifetime edge depends on lifetimes 'a
        let aEdges = [this];


        const result = wasm.LineSplitter_spliterator(this.ffiValue);

        try {
            return new Spliterator(diplomatRuntime.internalConstructor, result, [], aEdges);
        }

        finally {
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}