// generated by diplomat-tool
import type { Spliterator } from "./Spliterator"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class LineSplitter {
    get ffiValue(): pointer;


    static new_(input: string): LineSplitter;

    spliterator(): Spliterator;
}