// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class Wrapper {
    get ffiValue(): pointer;


    static new_(): Wrapper;

    returnInner(): string;

    ownedBytes(): string | null;
}